Ti_Fate/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Ti_Fate.Core.DbService.Interface;
using Ti_Fate.ViewModels;

namespace Ti_Fate.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly IProfileDbService _profileDbService;

        public ProfileController(IProfileDbService profileDbService)
        {
            _profileDbService = profileDbService;
        }

        public IActionResult Profile(int profileId)
        {
            var profileDomain = _profileDbService.GetProfile(profileId);
            var profileViewModel = new ProfileViewModel(profileDomain);
            return View(nameof(Profile), profileViewModel);
        }

    }
}

Ti_Fate/Controllers/SearchController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Ti_Fate.Core.Service.Interface;
using Ti_Fate.Models;
using Ti_Fate.ViewModels;

namespace Ti_Fate.Controllers
{
    [Authorize]
    public class SearchController : Controller
    {
        private readonly ISearchService _searchService;

        public SearchController(ISearchService searchService)
        {
            _searchService = searchService;
        }

        public IActionResult Index(string searchString)
        {
            var searchViewModel = new SearchViewModel(searchString);

            return View(nameof(Index), searchViewModel);
        }

        public IActionResult SearchInfos(string searchString)
        {
            var searchResult = _searchService.SearchInfos(searchString);
            return Json(searchResult);
        }

        public IActionResult SearchProfile(string searchString)
        {
            var searchResult = _searchService.SearchProfile(searchString);
            return Json(searchResult.Profile.Select(p=>new BasicProfileModel(p)));
        }
    }
}

Ti_Fate/Views/Shared/_Layout.cshtml
@using Ti_Fate.Core.DomainModel
@using Ti_Fate.Core.Service
@using Ti_Fate.Extensions
@{
    var loginSession = Context.Session.GetObject<LoginSession>("LoginSession");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <!-- Normalize CSS -->
    <link href="~/css/normalize.css" rel="stylesheet" />

    <link rel="apple-touch-icon" sizes="76x76" href="~/img/apple-icon.png">
    <link rel="icon" type="image/png" href="~/img/favicon.png">
    <title>
        Ti-Fate
    </title>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.11"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

    <!-- Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <!-- Nucleo Icons -->
    <link href="~/css/nucleo-icons.css" rel="stylesheet" />
    <!-- CSS Files -->
    <link href="~/css/black-dashboard.css?v=1.0.0" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
            crossorigin="anonymous"></script>

    <!-- include libraries(jQuery, bootstrap) -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <!-- include summernote css/js -->
    <link href="~/lib/summernote/summernote-lite.min.css" rel="stylesheet">
    <script src="~/lib/summernote/summernote-lite.min.js"></script>

    <!-- slick Files -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.css" />

    <!-- Moment v2.26.0-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.26.0/moment.min.js"></script>

</head>
<body>
    <div class="wrapper">
        <div class="sidebar">
            <div class="sidebar-wrapper">
                <ul class="nav" id="sidebar-menu">
                    <li v-for="item in menu">
                        <template v-if="item.permission">
                            <a v-on:click="toPage(item.url)">
                                <i :class="item.icon"></i>
                                <p>{{item.title}}</p>
                            </a>
                        </template>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
                <div class="container-fluid">
                    <div class="navbar-wrapper">
                        <div class="navbar-toggle d-inline">
                            <button type="button" class="navbar-toggler">
                                <span class="navbar-toggler-bar bar1"></span>
                                <span class="navbar-toggler-bar bar2"></span>
                                <span class="navbar-toggler-bar bar3"></span>
                            </button>
                        </div>
                        <a asp-controller="Home" asp-action="Home"><h2 class="font-weight-bolder" style="margin: 5px">Ti-Fate</h2></a>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navigation">
                        <div class="col-lg-10 custom-control-inline" style="padding: 0 12%">
                            <input type="text" id="search-string" class="form-control " placeholder="請輸入搜尋資料..." style="width: 100%">
                            <button type="submit" id="search-button" class="btn btn-link btn-icon btn-round btn-primary" onclick="search()">
                                <i class="tim-icons icon-zoom-split"></i>
                            </button>
                        </div>
                        <ul class="navbar-nav ml-auto">
                            <li class="dropdown nav-item">
                                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                                    <div class="photo">
                                        <img src="@Url.Content(loginSession.FirstPicturePath)" alt="Profile Photo">
                                    </div>
                                    <i class="caret d-none d-lg-block d-xl-block"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-navbar">
                                    <li class="nav-link"><a asp-controller="Profile" asp-action="Profile" asp-route-profileId="@loginSession.ProfileId" class="nav-item dropdown-item">個人資料</a></li>
                                    <li class="dropdown-divider"></li>
                                    <li class="nav-link"><a asp-area="" asp-controller="Home" asp-action="Logout" class="nav-item dropdown-item">登出</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- End Navbar -->
            <div class="content">
                @RenderBody()
            </div>
        </div>
    </div>
    <footer class="footer">
        <p>&copy; 2020 - Ti_Fate</p>
    </footer>

    <!--   Core JS Files   -->
    <script src="~/js/core/jquery.min.js" type="text/javascript"></script>
    <script src="~/js/core/popper.min.js" type="text/javascript"></script>
    <script src="~/js/core/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/js/plugins/perfect-scrollbar.jquery.min.js"></script>
    <!--  Notifications Plugin    -->
    <script src="~/js/plugins/bootstrap-notify.js"></script>
    <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="~/js/black-dashboard.js?v=1.0.0" type="text/javascript"></script>
    <script>
        $(document).ready(function() {
            $().ready(function() {
                var $sidebar = $('.sidebar');
                var $navbar = $('.navbar');
                var $mainPanel = $('.main-panel');

                var $fullPage = $('.full-page');

                var $sidebarResponsive = $('body > .navbar-collapse');
                var sidebarMiniActive = true;
                var whiteColor = false;

                var windowWidth = $(window).width();

                var fixedPluginOpen = $('.sidebar .sidebar-wrapper .nav li.active a p').html();


                $('.fixed-plugin a').click(function(event) {
                    if ($(this).hasClass('switch-trigger')) {
                        if (event.stopPropagation) {
                            event.stopPropagation();
                        } else if (window.event) {
                            window.event.cancelBubble = true;
                        }
                    }
                });


                $('.switch-sidebar-mini input').on("switchChange.bootstrapSwitch",
                    function() {
                        var $btn = $(this);

                        if (sidebarMiniActive === true) {
                            $('body').removeClass('sidebar-mini');
                            sidebarMiniActive = false;
                            blackDashboard.showSidebarMessage('Sidebar mini deactivated~.');
                        } else {
                            $('body').addClass('sidebar-mini');
                            sidebarMiniActive = true;
                            blackDashboard.showSidebarMessage('Sidebar mini activated~.');
                        }

                        // we simulate the window Resize so the charts will get updated in realtime.
                        var simulateWindowResize = setInterval(function() {
                                window.dispatchEvent(new Event('resize'));
                            },
                            180);

                        // we stop the simulation of Window Resize after the animations are completed
                        setTimeout(function() {
                                clearInterval(simulateWindowResize);
                            },
                            1000);
                    });
            });
        });

        function search() {
            var searchString = $('#search-string').val();
            if (searchString.length <= 10) {
            location.href = '@Url.Action("Index", "Search")' + '?searchString=' +searchString;
            } else {
                alert("Search String should be less than 10.");
            }
        }
    </script>
    <script src="https://cdn.trackjs.com/agent/v3/latest/t.js"></script>
    <script>
        window.TrackJS &&
            TrackJS.install({
                token: "ee6fab19c5a04ac1a32a645abde4613a",
                application: "black-dashboard-free"
            });

        $("#search-string").keypress(function (e) {
            if (e.which == 13) {
                $("#search-button").click();
            }
        });
    </script>
    <script>
        var app_sidebar = new Vue({
            el: "#sidebar-menu",
            data: {
                menu: [
                    {
                        title: "首頁",
                        icon: "tim-icons icon-chart-pie-36",
                        url: "@Url.Action("Home", "Home")",
                        permission: true
                    }, {
                        title: "福委公告",
                        icon: "tim-icons icon-pin",
                        url: "@Url.Action("Welfare", "Welfare")",
                        permission: true
                    }, {
                        title: "Meet Up",
                        icon: "tim-icons icon-atom",
                        url: "@Url.Action("MeetUpInfo", "MeetUpInfo")",
                        permission: true
                    }, {
                        title: "新人介紹",
                        icon: "tim-icons icon-shape-star",
                        url: "@Url.Action("NewComing", "NewComing")",
                        permission: true
                    }, {
                        title: "本月壽星",
                        icon: "tim-icons icon-gift-2",
                        url: "@Url.Action("Birthday","Birthday")",
                        permission: true
                    }, {
                        title: "社團資訊",
                        icon: "tim-icons icon-planet",
                        url: "@Url.Action("ClubsInfo","ClubsInfo")",
                        permission: true
                    }, {
                        title: "外部研討",
                        icon: "tim-icons icon-world",
                        url: "@Url.Action("ExternalInfo","ExternalInfo")",
                        permission: true
                    }, {
                        title: "特約商店公告",
                        icon: "tim-icons icon-basket-simple",
                        url: "@Url.Action("ComingSoon","Home")",
                        permission: true
                    }, {
                        title: "編輯使用者權限",
                        icon: "tim-icons icon-settings",
                        url: "@Url.Action("Index","ManagePermission")",
                        permission: "@PermissionsService.IsAdmin(loginSession.Permission)" === "True"
                    }
                ]
            },
            methods: {
                toPage: function(url) {
                    window.location.href = url;
                }
            }
        });
    </script>
</body>
@RenderSection("Scripts", required: false)
</html>